version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew clean build
      - sam validate --lint -t infra/app-only.yaml --region ap-northeast-1
      - sam validate --lint -t infra/template.yaml --region ap-northeast-1
      - sam package --template-file infra/app-only.yaml --s3-bucket $ARTIFACT_BUCKET --output-template-file packaged-template.yaml

artifacts:
  files:
    - packaged-template.yaml
